# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Fri Nov 11 12:00:39 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1915, 1104)
        self.centralwidget = QtGui.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1893, 1080))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.groupBox_condition = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_condition.setGeometry(QtCore.QRect(10, 920, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_condition.setFont(font)
        self.groupBox_condition.setObjectName(_fromUtf8("groupBox_condition"))
        self.label_condition = QtGui.QLabel(self.groupBox_condition)
        self.label_condition.setGeometry(QtCore.QRect(10, 20, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_condition.setFont(font)
        self.label_condition.setText(_fromUtf8(""))
        self.label_condition.setObjectName(_fromUtf8("label_condition"))
        self.groupBox_control = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_control.setEnabled(True)
        self.groupBox_control.setGeometry(QtCore.QRect(10, 560, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_control.setFont(font)
        self.groupBox_control.setObjectName(_fromUtf8("groupBox_control"))
        self.pushButton_Start = QtGui.QPushButton(self.groupBox_control)
        self.pushButton_Start.setGeometry(QtCore.QRect(30, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setObjectName(_fromUtf8("pushButton_Start"))
        self.pushButton_Pause = QtGui.QPushButton(self.groupBox_control)
        self.pushButton_Pause.setEnabled(False)
        self.pushButton_Pause.setGeometry(QtCore.QRect(130, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Pause.setFont(font)
        self.pushButton_Pause.setObjectName(_fromUtf8("pushButton_Pause"))
        self.pushButton_Stop = QtGui.QPushButton(self.groupBox_control)
        self.pushButton_Stop.setEnabled(False)
        self.pushButton_Stop.setGeometry(QtCore.QRect(230, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setObjectName(_fromUtf8("pushButton_Stop"))
        self.tabWidget_visa = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget_visa.setGeometry(QtCore.QRect(10, 10, 321, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_visa.setFont(font)
        self.tabWidget_visa.setObjectName(_fromUtf8("tabWidget_visa"))
        self.tab_228 = QtGui.QWidget()
        self.tab_228.setObjectName(_fromUtf8("tab_228"))
        self.label_chooseVisa_1 = QtGui.QLabel(self.tab_228)
        self.label_chooseVisa_1.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_1.setFont(font)
        self.label_chooseVisa_1.setObjectName(_fromUtf8("label_chooseVisa_1"))
        self.pushButton_select_1 = QtGui.QPushButton(self.tab_228)
        self.pushButton_select_1.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_1.setFont(font)
        self.pushButton_select_1.setObjectName(_fromUtf8("pushButton_select_1"))
        self.comboBox_visa_1 = QtGui.QComboBox(self.tab_228)
        self.comboBox_visa_1.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_1.setFont(font)
        self.comboBox_visa_1.setObjectName(_fromUtf8("comboBox_visa_1"))
        self.label_visaname_1 = QtGui.QLabel(self.tab_228)
        self.label_visaname_1.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_1.setFont(font)
        self.label_visaname_1.setObjectName(_fromUtf8("label_visaname_1"))
        self.pushButton_close_1 = QtGui.QPushButton(self.tab_228)
        self.pushButton_close_1.setEnabled(False)
        self.pushButton_close_1.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_1.setFont(font)
        self.pushButton_close_1.setObjectName(_fromUtf8("pushButton_close_1"))
        self.pushButton_update_1 = QtGui.QPushButton(self.tab_228)
        self.pushButton_update_1.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_1.setFont(font)
        self.pushButton_update_1.setObjectName(_fromUtf8("pushButton_update_1"))
        self.label_visa_1 = QtGui.QLabel(self.tab_228)
        self.label_visa_1.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_1.setFont(font)
        self.label_visa_1.setText(_fromUtf8(""))
        self.label_visa_1.setObjectName(_fromUtf8("label_visa_1"))
        self.tabWidget_visa.addTab(self.tab_228, _fromUtf8(""))
        self.tab_229 = QtGui.QWidget()
        self.tab_229.setObjectName(_fromUtf8("tab_229"))
        self.pushButton_update_2 = QtGui.QPushButton(self.tab_229)
        self.pushButton_update_2.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_2.setFont(font)
        self.pushButton_update_2.setObjectName(_fromUtf8("pushButton_update_2"))
        self.pushButton_close_2 = QtGui.QPushButton(self.tab_229)
        self.pushButton_close_2.setEnabled(False)
        self.pushButton_close_2.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_2.setFont(font)
        self.pushButton_close_2.setObjectName(_fromUtf8("pushButton_close_2"))
        self.pushButton_select_2 = QtGui.QPushButton(self.tab_229)
        self.pushButton_select_2.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_2.setFont(font)
        self.pushButton_select_2.setObjectName(_fromUtf8("pushButton_select_2"))
        self.comboBox_visa_2 = QtGui.QComboBox(self.tab_229)
        self.comboBox_visa_2.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_2.setFont(font)
        self.comboBox_visa_2.setObjectName(_fromUtf8("comboBox_visa_2"))
        self.label_visaname_2 = QtGui.QLabel(self.tab_229)
        self.label_visaname_2.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_2.setFont(font)
        self.label_visaname_2.setObjectName(_fromUtf8("label_visaname_2"))
        self.label_chooseVisa_2 = QtGui.QLabel(self.tab_229)
        self.label_chooseVisa_2.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_2.setFont(font)
        self.label_chooseVisa_2.setObjectName(_fromUtf8("label_chooseVisa_2"))
        self.label_visa_2 = QtGui.QLabel(self.tab_229)
        self.label_visa_2.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_2.setFont(font)
        self.label_visa_2.setText(_fromUtf8(""))
        self.label_visa_2.setObjectName(_fromUtf8("label_visa_2"))
        self.tabWidget_visa.addTab(self.tab_229, _fromUtf8(""))
        self.tab_230 = QtGui.QWidget()
        self.tab_230.setObjectName(_fromUtf8("tab_230"))
        self.pushButton_update_3 = QtGui.QPushButton(self.tab_230)
        self.pushButton_update_3.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_3.setFont(font)
        self.pushButton_update_3.setObjectName(_fromUtf8("pushButton_update_3"))
        self.pushButton_close_3 = QtGui.QPushButton(self.tab_230)
        self.pushButton_close_3.setEnabled(False)
        self.pushButton_close_3.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_3.setFont(font)
        self.pushButton_close_3.setObjectName(_fromUtf8("pushButton_close_3"))
        self.pushButton_select_3 = QtGui.QPushButton(self.tab_230)
        self.pushButton_select_3.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_3.setFont(font)
        self.pushButton_select_3.setObjectName(_fromUtf8("pushButton_select_3"))
        self.comboBox_visa_3 = QtGui.QComboBox(self.tab_230)
        self.comboBox_visa_3.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_3.setFont(font)
        self.comboBox_visa_3.setObjectName(_fromUtf8("comboBox_visa_3"))
        self.label_visaname_3 = QtGui.QLabel(self.tab_230)
        self.label_visaname_3.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_3.setFont(font)
        self.label_visaname_3.setObjectName(_fromUtf8("label_visaname_3"))
        self.label_chooseVisa_3 = QtGui.QLabel(self.tab_230)
        self.label_chooseVisa_3.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_3.setFont(font)
        self.label_chooseVisa_3.setObjectName(_fromUtf8("label_chooseVisa_3"))
        self.label_visa_3 = QtGui.QLabel(self.tab_230)
        self.label_visa_3.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_3.setFont(font)
        self.label_visa_3.setText(_fromUtf8(""))
        self.label_visa_3.setObjectName(_fromUtf8("label_visa_3"))
        self.tabWidget_visa.addTab(self.tab_230, _fromUtf8(""))
        self.tab_231 = QtGui.QWidget()
        self.tab_231.setObjectName(_fromUtf8("tab_231"))
        self.pushButton_update_4 = QtGui.QPushButton(self.tab_231)
        self.pushButton_update_4.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_4.setFont(font)
        self.pushButton_update_4.setObjectName(_fromUtf8("pushButton_update_4"))
        self.pushButton_close_4 = QtGui.QPushButton(self.tab_231)
        self.pushButton_close_4.setEnabled(False)
        self.pushButton_close_4.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_4.setFont(font)
        self.pushButton_close_4.setObjectName(_fromUtf8("pushButton_close_4"))
        self.pushButton_select_4 = QtGui.QPushButton(self.tab_231)
        self.pushButton_select_4.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_4.setFont(font)
        self.pushButton_select_4.setObjectName(_fromUtf8("pushButton_select_4"))
        self.comboBox_visa_4 = QtGui.QComboBox(self.tab_231)
        self.comboBox_visa_4.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_4.setFont(font)
        self.comboBox_visa_4.setObjectName(_fromUtf8("comboBox_visa_4"))
        self.label_visaname_4 = QtGui.QLabel(self.tab_231)
        self.label_visaname_4.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_4.setFont(font)
        self.label_visaname_4.setObjectName(_fromUtf8("label_visaname_4"))
        self.label_chooseVisa_4 = QtGui.QLabel(self.tab_231)
        self.label_chooseVisa_4.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_4.setFont(font)
        self.label_chooseVisa_4.setObjectName(_fromUtf8("label_chooseVisa_4"))
        self.label_visa_4 = QtGui.QLabel(self.tab_231)
        self.label_visa_4.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_4.setFont(font)
        self.label_visa_4.setText(_fromUtf8(""))
        self.label_visa_4.setObjectName(_fromUtf8("label_visa_4"))
        self.tabWidget_visa.addTab(self.tab_231, _fromUtf8(""))
        self.tab_232 = QtGui.QWidget()
        self.tab_232.setObjectName(_fromUtf8("tab_232"))
        self.pushButton_update_5 = QtGui.QPushButton(self.tab_232)
        self.pushButton_update_5.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_5.setFont(font)
        self.pushButton_update_5.setObjectName(_fromUtf8("pushButton_update_5"))
        self.pushButton_close_5 = QtGui.QPushButton(self.tab_232)
        self.pushButton_close_5.setEnabled(False)
        self.pushButton_close_5.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_5.setFont(font)
        self.pushButton_close_5.setObjectName(_fromUtf8("pushButton_close_5"))
        self.pushButton_select_5 = QtGui.QPushButton(self.tab_232)
        self.pushButton_select_5.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_5.setFont(font)
        self.pushButton_select_5.setObjectName(_fromUtf8("pushButton_select_5"))
        self.comboBox_visa_5 = QtGui.QComboBox(self.tab_232)
        self.comboBox_visa_5.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_5.setFont(font)
        self.comboBox_visa_5.setObjectName(_fromUtf8("comboBox_visa_5"))
        self.label_visaname_5 = QtGui.QLabel(self.tab_232)
        self.label_visaname_5.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_5.setFont(font)
        self.label_visaname_5.setObjectName(_fromUtf8("label_visaname_5"))
        self.label_chooseVisa_5 = QtGui.QLabel(self.tab_232)
        self.label_chooseVisa_5.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_5.setFont(font)
        self.label_chooseVisa_5.setObjectName(_fromUtf8("label_chooseVisa_5"))
        self.label_visa_5 = QtGui.QLabel(self.tab_232)
        self.label_visa_5.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_5.setFont(font)
        self.label_visa_5.setText(_fromUtf8(""))
        self.label_visa_5.setObjectName(_fromUtf8("label_visa_5"))
        self.tabWidget_visa.addTab(self.tab_232, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.comboBox_visa_6 = QtGui.QComboBox(self.tab)
        self.comboBox_visa_6.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_6.setFont(font)
        self.comboBox_visa_6.setObjectName(_fromUtf8("comboBox_visa_6"))
        self.pushButton_update_6 = QtGui.QPushButton(self.tab)
        self.pushButton_update_6.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_6.setFont(font)
        self.pushButton_update_6.setObjectName(_fromUtf8("pushButton_update_6"))
        self.label_visaname_6 = QtGui.QLabel(self.tab)
        self.label_visaname_6.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_6.setFont(font)
        self.label_visaname_6.setObjectName(_fromUtf8("label_visaname_6"))
        self.label_visa_6 = QtGui.QLabel(self.tab)
        self.label_visa_6.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_6.setFont(font)
        self.label_visa_6.setText(_fromUtf8(""))
        self.label_visa_6.setObjectName(_fromUtf8("label_visa_6"))
        self.pushButton_select_6 = QtGui.QPushButton(self.tab)
        self.pushButton_select_6.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_6.setFont(font)
        self.pushButton_select_6.setObjectName(_fromUtf8("pushButton_select_6"))
        self.label_chooseVisa_6 = QtGui.QLabel(self.tab)
        self.label_chooseVisa_6.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_6.setFont(font)
        self.label_chooseVisa_6.setObjectName(_fromUtf8("label_chooseVisa_6"))
        self.pushButton_close_6 = QtGui.QPushButton(self.tab)
        self.pushButton_close_6.setEnabled(False)
        self.pushButton_close_6.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_6.setFont(font)
        self.pushButton_close_6.setObjectName(_fromUtf8("pushButton_close_6"))
        self.tabWidget_visa.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.comboBox_visa_7 = QtGui.QComboBox(self.tab_2)
        self.comboBox_visa_7.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_7.setFont(font)
        self.comboBox_visa_7.setObjectName(_fromUtf8("comboBox_visa_7"))
        self.pushButton_update_7 = QtGui.QPushButton(self.tab_2)
        self.pushButton_update_7.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_7.setFont(font)
        self.pushButton_update_7.setObjectName(_fromUtf8("pushButton_update_7"))
        self.label_visaname_7 = QtGui.QLabel(self.tab_2)
        self.label_visaname_7.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_7.setFont(font)
        self.label_visaname_7.setObjectName(_fromUtf8("label_visaname_7"))
        self.label_visa_7 = QtGui.QLabel(self.tab_2)
        self.label_visa_7.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_7.setFont(font)
        self.label_visa_7.setText(_fromUtf8(""))
        self.label_visa_7.setObjectName(_fromUtf8("label_visa_7"))
        self.pushButton_select_7 = QtGui.QPushButton(self.tab_2)
        self.pushButton_select_7.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_7.setFont(font)
        self.pushButton_select_7.setObjectName(_fromUtf8("pushButton_select_7"))
        self.label_chooseVisa_7 = QtGui.QLabel(self.tab_2)
        self.label_chooseVisa_7.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_7.setFont(font)
        self.label_chooseVisa_7.setObjectName(_fromUtf8("label_chooseVisa_7"))
        self.pushButton_close_7 = QtGui.QPushButton(self.tab_2)
        self.pushButton_close_7.setEnabled(False)
        self.pushButton_close_7.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_7.setFont(font)
        self.pushButton_close_7.setObjectName(_fromUtf8("pushButton_close_7"))
        self.tabWidget_visa.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.comboBox_visa_8 = QtGui.QComboBox(self.tab_3)
        self.comboBox_visa_8.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_8.setFont(font)
        self.comboBox_visa_8.setObjectName(_fromUtf8("comboBox_visa_8"))
        self.pushButton_update_8 = QtGui.QPushButton(self.tab_3)
        self.pushButton_update_8.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_8.setFont(font)
        self.pushButton_update_8.setObjectName(_fromUtf8("pushButton_update_8"))
        self.label_visaname_8 = QtGui.QLabel(self.tab_3)
        self.label_visaname_8.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_8.setFont(font)
        self.label_visaname_8.setObjectName(_fromUtf8("label_visaname_8"))
        self.label_visa_8 = QtGui.QLabel(self.tab_3)
        self.label_visa_8.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_8.setFont(font)
        self.label_visa_8.setText(_fromUtf8(""))
        self.label_visa_8.setObjectName(_fromUtf8("label_visa_8"))
        self.pushButton_select_8 = QtGui.QPushButton(self.tab_3)
        self.pushButton_select_8.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_8.setFont(font)
        self.pushButton_select_8.setObjectName(_fromUtf8("pushButton_select_8"))
        self.label_chooseVisa_8 = QtGui.QLabel(self.tab_3)
        self.label_chooseVisa_8.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_8.setFont(font)
        self.label_chooseVisa_8.setObjectName(_fromUtf8("label_chooseVisa_8"))
        self.pushButton_close_8 = QtGui.QPushButton(self.tab_3)
        self.pushButton_close_8.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_8.setFont(font)
        self.pushButton_close_8.setObjectName(_fromUtf8("pushButton_close_8"))
        self.tabWidget_visa.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.comboBox_visa_9 = QtGui.QComboBox(self.tab_4)
        self.comboBox_visa_9.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_9.setFont(font)
        self.comboBox_visa_9.setObjectName(_fromUtf8("comboBox_visa_9"))
        self.pushButton_update_9 = QtGui.QPushButton(self.tab_4)
        self.pushButton_update_9.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_9.setFont(font)
        self.pushButton_update_9.setObjectName(_fromUtf8("pushButton_update_9"))
        self.label_visaname_9 = QtGui.QLabel(self.tab_4)
        self.label_visaname_9.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_9.setFont(font)
        self.label_visaname_9.setObjectName(_fromUtf8("label_visaname_9"))
        self.label_visa_9 = QtGui.QLabel(self.tab_4)
        self.label_visa_9.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_9.setFont(font)
        self.label_visa_9.setText(_fromUtf8(""))
        self.label_visa_9.setObjectName(_fromUtf8("label_visa_9"))
        self.pushButton_select_9 = QtGui.QPushButton(self.tab_4)
        self.pushButton_select_9.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_9.setFont(font)
        self.pushButton_select_9.setObjectName(_fromUtf8("pushButton_select_9"))
        self.label_chooseVisa_9 = QtGui.QLabel(self.tab_4)
        self.label_chooseVisa_9.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_9.setFont(font)
        self.label_chooseVisa_9.setObjectName(_fromUtf8("label_chooseVisa_9"))
        self.pushButton_close_9 = QtGui.QPushButton(self.tab_4)
        self.pushButton_close_9.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_9.setFont(font)
        self.pushButton_close_9.setObjectName(_fromUtf8("pushButton_close_9"))
        self.tabWidget_visa.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.comboBox_visa_10 = QtGui.QComboBox(self.tab_5)
        self.comboBox_visa_10.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_10.setFont(font)
        self.comboBox_visa_10.setObjectName(_fromUtf8("comboBox_visa_10"))
        self.pushButton_update_10 = QtGui.QPushButton(self.tab_5)
        self.pushButton_update_10.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_10.setFont(font)
        self.pushButton_update_10.setObjectName(_fromUtf8("pushButton_update_10"))
        self.label_visaname_10 = QtGui.QLabel(self.tab_5)
        self.label_visaname_10.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_10.setFont(font)
        self.label_visaname_10.setObjectName(_fromUtf8("label_visaname_10"))
        self.label_visa_10 = QtGui.QLabel(self.tab_5)
        self.label_visa_10.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_10.setFont(font)
        self.label_visa_10.setText(_fromUtf8(""))
        self.label_visa_10.setObjectName(_fromUtf8("label_visa_10"))
        self.pushButton_select_10 = QtGui.QPushButton(self.tab_5)
        self.pushButton_select_10.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_10.setFont(font)
        self.pushButton_select_10.setObjectName(_fromUtf8("pushButton_select_10"))
        self.label_chooseVisa_10 = QtGui.QLabel(self.tab_5)
        self.label_chooseVisa_10.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_10.setFont(font)
        self.label_chooseVisa_10.setObjectName(_fromUtf8("label_chooseVisa_10"))
        self.pushButton_close_10 = QtGui.QPushButton(self.tab_5)
        self.pushButton_close_10.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_10.setFont(font)
        self.pushButton_close_10.setObjectName(_fromUtf8("pushButton_close_10"))
        self.tabWidget_visa.addTab(self.tab_5, _fromUtf8(""))
        self.textEdit = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setGeometry(QtCore.QRect(10, 240, 321, 311))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.textEditDisplay = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.textEditDisplay.setGeometry(QtCore.QRect(10, 630, 321, 281))
        self.textEditDisplay.setObjectName(_fromUtf8("textEditDisplay"))
        self.tabWidget = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(340, 10, 1551, 961))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_213 = QtGui.QWidget()
        self.tab_213.setObjectName(_fromUtf8("tab_213"))
        self.gridLayout_40 = QtGui.QGridLayout(self.tab_213)
        self.gridLayout_40.setObjectName(_fromUtf8("gridLayout_40"))
        self.scrollArea_1 = QtGui.QScrollArea(self.tab_213)
        self.scrollArea_1.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_1.setSizeIncrement(QtCore.QSize(0, 0))
        self.scrollArea_1.setBaseSize(QtCore.QSize(0, 0))
        self.scrollArea_1.setAutoFillBackground(False)
        self.scrollArea_1.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_1.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_1.setWidgetResizable(False)
        self.scrollArea_1.setObjectName(_fromUtf8("scrollArea_1"))
        self.scrollAreaWidgetContents_47 = QtGui.QWidget()
        self.scrollAreaWidgetContents_47.setGeometry(QtCore.QRect(0, 0, 4351, 900))
        self.scrollAreaWidgetContents_47.setObjectName(_fromUtf8("scrollAreaWidgetContents_47"))
        self.curvewidget_1 = CurveWidget(self.scrollAreaWidgetContents_47)
        self.curvewidget_1.setGeometry(QtCore.QRect(0, 10, 711, 401))
        self.curvewidget_1.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_1.setObjectName(_fromUtf8("curvewidget_1"))
        self.curvewidget_3 = CurveWidget(self.scrollAreaWidgetContents_47)
        self.curvewidget_3.setGeometry(QtCore.QRect(720, 10, 711, 401))
        self.curvewidget_3.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_3.setObjectName(_fromUtf8("curvewidget_3"))
        self.curvewidget_2 = CurveWidget(self.scrollAreaWidgetContents_47)
        self.curvewidget_2.setGeometry(QtCore.QRect(0, 460, 711, 401))
        self.curvewidget_2.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_2.setObjectName(_fromUtf8("curvewidget_2"))
        self.curvewidget_4 = CurveWidget(self.scrollAreaWidgetContents_47)
        self.curvewidget_4.setGeometry(QtCore.QRect(720, 460, 711, 401))
        self.curvewidget_4.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_4.setObjectName(_fromUtf8("curvewidget_4"))
        self.curvewidget_7 = CurveWidget(self.scrollAreaWidgetContents_47)
        self.curvewidget_7.setGeometry(QtCore.QRect(2160, 10, 711, 401))
        self.curvewidget_7.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_7.setObjectName(_fromUtf8("curvewidget_7"))
        self.curvewidget_6 = CurveWidget(self.scrollAreaWidgetContents_47)
        self.curvewidget_6.setGeometry(QtCore.QRect(1440, 460, 711, 401))
        self.curvewidget_6.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_6.setObjectName(_fromUtf8("curvewidget_6"))
        self.curvewidget_8 = CurveWidget(self.scrollAreaWidgetContents_47)
        self.curvewidget_8.setGeometry(QtCore.QRect(2160, 460, 711, 401))
        self.curvewidget_8.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_8.setObjectName(_fromUtf8("curvewidget_8"))
        self.curvewidget_5 = CurveWidget(self.scrollAreaWidgetContents_47)
        self.curvewidget_5.setGeometry(QtCore.QRect(1440, 10, 711, 401))
        self.curvewidget_5.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_5.setObjectName(_fromUtf8("curvewidget_5"))
        self.curvewidget_11 = CurveWidget(self.scrollAreaWidgetContents_47)
        self.curvewidget_11.setGeometry(QtCore.QRect(3620, 10, 711, 401))
        self.curvewidget_11.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_11.setObjectName(_fromUtf8("curvewidget_11"))
        self.curvewidget_10 = CurveWidget(self.scrollAreaWidgetContents_47)
        self.curvewidget_10.setGeometry(QtCore.QRect(2880, 460, 711, 401))
        self.curvewidget_10.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_10.setObjectName(_fromUtf8("curvewidget_10"))
        self.curvewidget_12 = CurveWidget(self.scrollAreaWidgetContents_47)
        self.curvewidget_12.setGeometry(QtCore.QRect(3620, 460, 711, 401))
        self.curvewidget_12.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_12.setObjectName(_fromUtf8("curvewidget_12"))
        self.curvewidget_9 = CurveWidget(self.scrollAreaWidgetContents_47)
        self.curvewidget_9.setGeometry(QtCore.QRect(2890, 10, 711, 401))
        self.curvewidget_9.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_9.setObjectName(_fromUtf8("curvewidget_9"))
        self.scrollArea_1.setWidget(self.scrollAreaWidgetContents_47)
        self.gridLayout_40.addWidget(self.scrollArea_1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_213, _fromUtf8(""))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.groupBox_dsave = QtGui.QGroupBox(self.tab_9)
        self.groupBox_dsave.setEnabled(True)
        self.groupBox_dsave.setGeometry(QtCore.QRect(490, 110, 581, 541))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_dsave.setFont(font)
        self.groupBox_dsave.setObjectName(_fromUtf8("groupBox_dsave"))
        self.label_dsave_directory = QtGui.QLabel(self.groupBox_dsave)
        self.label_dsave_directory.setEnabled(False)
        self.label_dsave_directory.setGeometry(QtCore.QRect(20, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dsave_directory.setFont(font)
        self.label_dsave_directory.setObjectName(_fromUtf8("label_dsave_directory"))
        self.lineEdit_dsave_directory = QtGui.QLineEdit(self.groupBox_dsave)
        self.lineEdit_dsave_directory.setEnabled(False)
        self.lineEdit_dsave_directory.setGeometry(QtCore.QRect(110, 80, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_dsave_directory.setFont(font)
        self.lineEdit_dsave_directory.setObjectName(_fromUtf8("lineEdit_dsave_directory"))
        self.checkBox_dsave = QtGui.QCheckBox(self.groupBox_dsave)
        self.checkBox_dsave.setEnabled(True)
        self.checkBox_dsave.setGeometry(QtCore.QRect(210, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_dsave.setFont(font)
        self.checkBox_dsave.setObjectName(_fromUtf8("checkBox_dsave"))
        self.label_dsave_username = QtGui.QLabel(self.groupBox_dsave)
        self.label_dsave_username.setEnabled(False)
        self.label_dsave_username.setGeometry(QtCore.QRect(20, 300, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dsave_username.setFont(font)
        self.label_dsave_username.setObjectName(_fromUtf8("label_dsave_username"))
        self.lineEdit_dsave_username = QtGui.QLineEdit(self.groupBox_dsave)
        self.lineEdit_dsave_username.setEnabled(False)
        self.lineEdit_dsave_username.setGeometry(QtCore.QRect(130, 300, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_dsave_username.setFont(font)
        self.lineEdit_dsave_username.setObjectName(_fromUtf8("lineEdit_dsave_username"))
        self.pushButton_dsave_browse = QtGui.QPushButton(self.groupBox_dsave)
        self.pushButton_dsave_browse.setEnabled(False)
        self.pushButton_dsave_browse.setGeometry(QtCore.QRect(400, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_dsave_browse.setFont(font)
        self.pushButton_dsave_browse.setObjectName(_fromUtf8("pushButton_dsave_browse"))
        self.label_dsave_comment = QtGui.QLabel(self.groupBox_dsave)
        self.label_dsave_comment.setEnabled(False)
        self.label_dsave_comment.setGeometry(QtCore.QRect(20, 350, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dsave_comment.setFont(font)
        self.label_dsave_comment.setObjectName(_fromUtf8("label_dsave_comment"))
        self.textEdit_dsave_comment = QtGui.QTextEdit(self.groupBox_dsave)
        self.textEdit_dsave_comment.setEnabled(False)
        self.textEdit_dsave_comment.setGeometry(QtCore.QRect(130, 360, 421, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_dsave_comment.setFont(font)
        self.textEdit_dsave_comment.setObjectName(_fromUtf8("textEdit_dsave_comment"))
        self.groupBox_dsave_filename = QtGui.QGroupBox(self.groupBox_dsave)
        self.groupBox_dsave_filename.setEnabled(False)
        self.groupBox_dsave_filename.setGeometry(QtCore.QRect(40, 140, 251, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_dsave_filename.setFont(font)
        self.groupBox_dsave_filename.setObjectName(_fromUtf8("groupBox_dsave_filename"))
        self.radioButton_dsave_timename = QtGui.QRadioButton(self.groupBox_dsave_filename)
        self.radioButton_dsave_timename.setEnabled(False)
        self.radioButton_dsave_timename.setGeometry(QtCore.QRect(30, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_dsave_timename.setFont(font)
        self.radioButton_dsave_timename.setChecked(True)
        self.radioButton_dsave_timename.setObjectName(_fromUtf8("radioButton_dsave_timename"))
        self.radioButton_dsave_custname = QtGui.QRadioButton(self.groupBox_dsave_filename)
        self.radioButton_dsave_custname.setEnabled(False)
        self.radioButton_dsave_custname.setGeometry(QtCore.QRect(30, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_dsave_custname.setFont(font)
        self.radioButton_dsave_custname.setObjectName(_fromUtf8("radioButton_dsave_custname"))
        self.lineEdit_dsave_custname = QtGui.QLineEdit(self.groupBox_dsave_filename)
        self.lineEdit_dsave_custname.setEnabled(False)
        self.lineEdit_dsave_custname.setGeometry(QtCore.QRect(50, 80, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_dsave_custname.setFont(font)
        self.lineEdit_dsave_custname.setObjectName(_fromUtf8("lineEdit_dsave_custname"))
        self.groupBox_dsave_filetype = QtGui.QGroupBox(self.groupBox_dsave)
        self.groupBox_dsave_filetype.setEnabled(False)
        self.groupBox_dsave_filetype.setGeometry(QtCore.QRect(330, 190, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_dsave_filetype.setFont(font)
        self.groupBox_dsave_filetype.setObjectName(_fromUtf8("groupBox_dsave_filetype"))
        self.radioButton_csv = QtGui.QRadioButton(self.groupBox_dsave_filetype)
        self.radioButton_csv.setEnabled(False)
        self.radioButton_csv.setGeometry(QtCore.QRect(40, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_csv.setFont(font)
        self.radioButton_csv.setAcceptDrops(False)
        self.radioButton_csv.setAutoFillBackground(False)
        self.radioButton_csv.setChecked(True)
        self.radioButton_csv.setObjectName(_fromUtf8("radioButton_csv"))
        self.radioButton_txt = QtGui.QRadioButton(self.groupBox_dsave_filetype)
        self.radioButton_txt.setGeometry(QtCore.QRect(130, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_txt.setFont(font)
        self.radioButton_txt.setObjectName(_fromUtf8("radioButton_txt"))
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_6)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 10, 1527, 911))
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.scrollArea_2.setBaseSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setAutoFillBackground(False)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_48 = QtGui.QWidget()
        self.scrollAreaWidgetContents_48.setGeometry(QtCore.QRect(0, 0, 4351, 900))
        self.scrollAreaWidgetContents_48.setObjectName(_fromUtf8("scrollAreaWidgetContents_48"))
        self.curvewidget_13 = CurveWidget(self.scrollAreaWidgetContents_48)
        self.curvewidget_13.setGeometry(QtCore.QRect(0, 10, 711, 401))
        self.curvewidget_13.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_13.setObjectName(_fromUtf8("curvewidget_13"))
        self.curvewidget_14 = CurveWidget(self.scrollAreaWidgetContents_48)
        self.curvewidget_14.setGeometry(QtCore.QRect(720, 10, 711, 401))
        self.curvewidget_14.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_14.setObjectName(_fromUtf8("curvewidget_14"))
        self.curvewidget_15 = CurveWidget(self.scrollAreaWidgetContents_48)
        self.curvewidget_15.setGeometry(QtCore.QRect(0, 460, 711, 401))
        self.curvewidget_15.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_15.setObjectName(_fromUtf8("curvewidget_15"))
        self.curvewidget_16 = CurveWidget(self.scrollAreaWidgetContents_48)
        self.curvewidget_16.setGeometry(QtCore.QRect(720, 460, 711, 401))
        self.curvewidget_16.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_16.setObjectName(_fromUtf8("curvewidget_16"))
        self.curvewidget_17 = CurveWidget(self.scrollAreaWidgetContents_48)
        self.curvewidget_17.setGeometry(QtCore.QRect(2160, 10, 711, 401))
        self.curvewidget_17.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_17.setObjectName(_fromUtf8("curvewidget_17"))
        self.curvewidget_18 = CurveWidget(self.scrollAreaWidgetContents_48)
        self.curvewidget_18.setGeometry(QtCore.QRect(1440, 460, 711, 401))
        self.curvewidget_18.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_18.setObjectName(_fromUtf8("curvewidget_18"))
        self.curvewidget_19 = CurveWidget(self.scrollAreaWidgetContents_48)
        self.curvewidget_19.setGeometry(QtCore.QRect(2160, 460, 711, 401))
        self.curvewidget_19.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_19.setObjectName(_fromUtf8("curvewidget_19"))
        self.curvewidget_20 = CurveWidget(self.scrollAreaWidgetContents_48)
        self.curvewidget_20.setGeometry(QtCore.QRect(1440, 10, 711, 401))
        self.curvewidget_20.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_20.setObjectName(_fromUtf8("curvewidget_20"))
        self.curvewidget_21 = CurveWidget(self.scrollAreaWidgetContents_48)
        self.curvewidget_21.setGeometry(QtCore.QRect(3620, 10, 711, 401))
        self.curvewidget_21.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_21.setObjectName(_fromUtf8("curvewidget_21"))
        self.curvewidget_22 = CurveWidget(self.scrollAreaWidgetContents_48)
        self.curvewidget_22.setGeometry(QtCore.QRect(2880, 460, 711, 401))
        self.curvewidget_22.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_22.setObjectName(_fromUtf8("curvewidget_22"))
        self.curvewidget_23 = CurveWidget(self.scrollAreaWidgetContents_48)
        self.curvewidget_23.setGeometry(QtCore.QRect(3620, 460, 711, 401))
        self.curvewidget_23.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_23.setObjectName(_fromUtf8("curvewidget_23"))
        self.curvewidget_24 = CurveWidget(self.scrollAreaWidgetContents_48)
        self.curvewidget_24.setGeometry(QtCore.QRect(2890, 10, 711, 401))
        self.curvewidget_24.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_24.setObjectName(_fromUtf8("curvewidget_24"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_48)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionArray_Builder = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionArray_Builder.setFont(font)
        self.actionArray_Builder.setObjectName(_fromUtf8("actionArray_Builder"))
        self.actionAgilent_Single_scan = QtGui.QAction(MainWindow)
        self.actionAgilent_Single_scan.setObjectName(_fromUtf8("actionAgilent_Single_scan"))
        self.actionKeithley_Single_scan = QtGui.QAction(MainWindow)
        self.actionKeithley_Single_scan.setObjectName(_fromUtf8("actionKeithley_Single_scan"))
        self.actionKeithley__Sweep = QtGui.QAction(MainWindow)
        self.actionKeithley__Sweep.setObjectName(_fromUtf8("actionKeithley__Sweep"))
        self.actionLockIn_Single_Scan = QtGui.QAction(MainWindow)
        self.actionLockIn_Single_Scan.setObjectName(_fromUtf8("actionLockIn_Single_Scan"))
        self.actionResonant_Single_Scan = QtGui.QAction(MainWindow)
        self.actionResonant_Single_Scan.setObjectName(_fromUtf8("actionResonant_Single_Scan"))
        self.actionKeithley_Stepper_Single_Scan = QtGui.QAction(MainWindow)
        self.actionKeithley_Stepper_Single_Scan.setObjectName(_fromUtf8("actionKeithley_Stepper_Single_Scan"))
        self.actionSee_Visa_List = QtGui.QAction(MainWindow)
        self.actionSee_Visa_List.setObjectName(_fromUtf8("actionSee_Visa_List"))
        self.actionTwo_s_with_Lock_in = QtGui.QAction(MainWindow)
        self.actionTwo_s_with_Lock_in.setObjectName(_fromUtf8("actionTwo_s_with_Lock_in"))
        self.actionSweep_Scan = QtGui.QAction(MainWindow)
        self.actionSweep_Scan.setObjectName(_fromUtf8("actionSweep_Scan"))
        self.actionLockInSweep = QtGui.QAction(MainWindow)
        self.actionLockInSweep.setObjectName(_fromUtf8("actionLockInSweep"))
        self.actionDouble_Lock_In = QtGui.QAction(MainWindow)
        self.actionDouble_Lock_In.setObjectName(_fromUtf8("actionDouble_Lock_In"))
        self.actionVoltage_Bias = QtGui.QAction(MainWindow)
        self.actionVoltage_Bias.setObjectName(_fromUtf8("actionVoltage_Bias"))
        self.actionCurrent_Bias = QtGui.QAction(MainWindow)
        self.actionCurrent_Bias.setObjectName(_fromUtf8("actionCurrent_Bias"))
        self.actionJV_1 = QtGui.QAction(MainWindow)
        self.actionJV_1.setObjectName(_fromUtf8("actionJV_1"))
        self.actionJV_2 = QtGui.QAction(MainWindow)
        self.actionJV_2.setObjectName(_fromUtf8("actionJV_2"))
        self.actionJV_3 = QtGui.QAction(MainWindow)
        self.actionJV_3.setObjectName(_fromUtf8("actionJV_3"))
        self.actionJS_1 = QtGui.QAction(MainWindow)
        self.actionJS_1.setObjectName(_fromUtf8("actionJS_1"))
        self.actionJS_2 = QtGui.QAction(MainWindow)
        self.actionJS_2.setObjectName(_fromUtf8("actionJS_2"))
        self.actionRS_1 = QtGui.QAction(MainWindow)
        self.actionRS_1.setObjectName(_fromUtf8("actionRS_1"))
        self.actionRS_2 = QtGui.QAction(MainWindow)
        self.actionRS_2.setObjectName(_fromUtf8("actionRS_2"))
        self.actionJS_3 = QtGui.QAction(MainWindow)
        self.actionJS_3.setObjectName(_fromUtf8("actionJS_3"))
        self.actionRS_3 = QtGui.QAction(MainWindow)
        self.actionRS_3.setObjectName(_fromUtf8("actionRS_3"))
        self.actionBW_1 = QtGui.QAction(MainWindow)
        self.actionBW_1.setObjectName(_fromUtf8("actionBW_1"))
        self.actionBW_2 = QtGui.QAction(MainWindow)
        self.actionBW_2.setObjectName(_fromUtf8("actionBW_2"))
        self.actionBW_3 = QtGui.QAction(MainWindow)
        self.actionBW_3.setObjectName(_fromUtf8("actionBW_3"))
        self.actionST_1 = QtGui.QAction(MainWindow)
        self.actionST_1.setObjectName(_fromUtf8("actionST_1"))
        self.actionST_2 = QtGui.QAction(MainWindow)
        self.actionST_2.setObjectName(_fromUtf8("actionST_2"))
        self.actionST_3 = QtGui.QAction(MainWindow)
        self.actionST_3.setObjectName(_fromUtf8("actionST_3"))

        self.retranslateUi(MainWindow)
        self.tabWidget_visa.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_condition.setTitle(_translate("MainWindow", "Condition", None))
        self.groupBox_control.setTitle(_translate("MainWindow", "Control", None))
        self.pushButton_Start.setText(_translate("MainWindow", "Start", None))
        self.pushButton_Pause.setText(_translate("MainWindow", "Pause", None))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop", None))
        self.label_chooseVisa_1.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.pushButton_select_1.setText(_translate("MainWindow", "Select", None))
        self.label_visaname_1.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_close_1.setText(_translate("MainWindow", "Close", None))
        self.pushButton_update_1.setText(_translate("MainWindow", "Update", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_228), _translate("MainWindow", "Yokogawa1", None))
        self.pushButton_update_2.setText(_translate("MainWindow", "Update", None))
        self.pushButton_close_2.setText(_translate("MainWindow", "Close", None))
        self.pushButton_select_2.setText(_translate("MainWindow", "Select", None))
        self.label_visaname_2.setText(_translate("MainWindow", "VISA name:", None))
        self.label_chooseVisa_2.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_229), _translate("MainWindow", "Agilent1", None))
        self.pushButton_update_3.setText(_translate("MainWindow", "Update", None))
        self.pushButton_close_3.setText(_translate("MainWindow", "Close", None))
        self.pushButton_select_3.setText(_translate("MainWindow", "Select", None))
        self.label_visaname_3.setText(_translate("MainWindow", "VISA name:", None))
        self.label_chooseVisa_3.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_230), _translate("MainWindow", "Yokogawa2", None))
        self.pushButton_update_4.setText(_translate("MainWindow", "Update", None))
        self.pushButton_close_4.setText(_translate("MainWindow", "Close", None))
        self.pushButton_select_4.setText(_translate("MainWindow", "Select", None))
        self.label_visaname_4.setText(_translate("MainWindow", "VISA name:", None))
        self.label_chooseVisa_4.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_231), _translate("MainWindow", "Agilent2", None))
        self.pushButton_update_5.setText(_translate("MainWindow", "Update", None))
        self.pushButton_close_5.setText(_translate("MainWindow", "Close", None))
        self.pushButton_select_5.setText(_translate("MainWindow", "Select", None))
        self.label_visaname_5.setText(_translate("MainWindow", "VISA name:", None))
        self.label_chooseVisa_5.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_232), _translate("MainWindow", "Yokogawa3", None))
        self.pushButton_update_6.setText(_translate("MainWindow", "Update", None))
        self.label_visaname_6.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_select_6.setText(_translate("MainWindow", "Select", None))
        self.label_chooseVisa_6.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.pushButton_close_6.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab), _translate("MainWindow", "Agilent3", None))
        self.pushButton_update_7.setText(_translate("MainWindow", "Update", None))
        self.label_visaname_7.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_select_7.setText(_translate("MainWindow", "Select", None))
        self.label_chooseVisa_7.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.pushButton_close_7.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_2), _translate("MainWindow", "Magnet", None))
        self.pushButton_update_8.setText(_translate("MainWindow", "Update", None))
        self.label_visaname_8.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_select_8.setText(_translate("MainWindow", "Select", None))
        self.label_chooseVisa_8.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.pushButton_close_8.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_3), _translate("MainWindow", "Visa8", None))
        self.pushButton_update_9.setText(_translate("MainWindow", "Update", None))
        self.label_visaname_9.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_select_9.setText(_translate("MainWindow", "Select", None))
        self.label_chooseVisa_9.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.pushButton_close_9.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_4), _translate("MainWindow", "Visa9", None))
        self.pushButton_update_10.setText(_translate("MainWindow", "Update", None))
        self.label_visaname_10.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_select_10.setText(_translate("MainWindow", "Select", None))
        self.label_chooseVisa_10.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.pushButton_close_10.setText(_translate("MainWindow", "Close", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_5), _translate("MainWindow", "Visa10", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_213), _translate("MainWindow", "Preview", None))
        self.groupBox_dsave.setTitle(_translate("MainWindow", "Dynamic Saving", None))
        self.label_dsave_directory.setText(_translate("MainWindow", "Directory:", None))
        self.checkBox_dsave.setText(_translate("MainWindow", "Dynamic Save", None))
        self.label_dsave_username.setText(_translate("MainWindow", "User Name:", None))
        self.pushButton_dsave_browse.setText(_translate("MainWindow", "Browse", None))
        self.label_dsave_comment.setText(_translate("MainWindow", "Comment:", None))
        self.groupBox_dsave_filename.setTitle(_translate("MainWindow", "File Name", None))
        self.radioButton_dsave_timename.setText(_translate("MainWindow", "Date and time", None))
        self.radioButton_dsave_custname.setText(_translate("MainWindow", "Custom", None))
        self.groupBox_dsave_filetype.setTitle(_translate("MainWindow", "File Type", None))
        self.radioButton_csv.setText(_translate("MainWindow", "csv", None))
        self.radioButton_txt.setText(_translate("MainWindow", "txt", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Saving", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Plot", None))
        self.actionArray_Builder.setText(_translate("MainWindow", "Array Builder", None))
        self.actionAgilent_Single_scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionKeithley_Single_scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionKeithley__Sweep.setText(_translate("MainWindow", " Sweep", None))
        self.actionLockIn_Single_Scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionResonant_Single_Scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionKeithley_Stepper_Single_Scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionSee_Visa_List.setText(_translate("MainWindow", "See Visa List", None))
        self.actionTwo_s_with_Lock_in.setText(_translate("MainWindow", "Two s with Lock-in", None))
        self.actionSweep_Scan.setText(_translate("MainWindow", "Sweep Scan", None))
        self.actionLockInSweep.setText(_translate("MainWindow", "Sweep Scan", None))
        self.actionDouble_Lock_In.setText(_translate("MainWindow", "Double Lock-In", None))
        self.actionVoltage_Bias.setText(_translate("MainWindow", "Voltage", None))
        self.actionCurrent_Bias.setText(_translate("MainWindow", "Current", None))
        self.actionJV_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionJV_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionJV_3.setText(_translate("MainWindow", "Program 3", None))
        self.actionJS_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionJS_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionRS_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionRS_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionJS_3.setText(_translate("MainWindow", "Program 3", None))
        self.actionRS_3.setText(_translate("MainWindow", "Program 3", None))
        self.actionBW_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionBW_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionBW_3.setText(_translate("MainWindow", "Program 3", None))
        self.actionST_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionST_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionST_3.setText(_translate("MainWindow", "Program 3", None))

from guiqwt.plot import CurveWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

