# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created: Thu Jul 21 15:23:47 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1838, 922)
        self.centralwidget = QtGui.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1816, 898))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.groupBox_condition = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_condition.setGeometry(QtCore.QRect(10, 670, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_condition.setFont(font)
        self.groupBox_condition.setObjectName(_fromUtf8("groupBox_condition"))
        self.label_condition = QtGui.QLabel(self.groupBox_condition)
        self.label_condition.setGeometry(QtCore.QRect(10, 20, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_condition.setFont(font)
        self.label_condition.setText(_fromUtf8(""))
        self.label_condition.setObjectName(_fromUtf8("label_condition"))
        self.groupBox_control = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_control.setEnabled(True)
        self.groupBox_control.setGeometry(QtCore.QRect(10, 350, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_control.setFont(font)
        self.groupBox_control.setObjectName(_fromUtf8("groupBox_control"))
        self.pushButton_Start = QtGui.QPushButton(self.groupBox_control)
        self.pushButton_Start.setGeometry(QtCore.QRect(30, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setObjectName(_fromUtf8("pushButton_Start"))
        self.pushButton_Pause = QtGui.QPushButton(self.groupBox_control)
        self.pushButton_Pause.setGeometry(QtCore.QRect(130, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Pause.setFont(font)
        self.pushButton_Pause.setObjectName(_fromUtf8("pushButton_Pause"))
        self.pushButton_Stop = QtGui.QPushButton(self.groupBox_control)
        self.pushButton_Stop.setGeometry(QtCore.QRect(230, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setObjectName(_fromUtf8("pushButton_Stop"))
        self.groupBox_parameters = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_parameters.setEnabled(True)
        self.groupBox_parameters.setGeometry(QtCore.QRect(10, 420, 321, 241))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_parameters.setFont(font)
        self.groupBox_parameters.setObjectName(_fromUtf8("groupBox_parameters"))
        self.label_V1 = QtGui.QLabel(self.groupBox_parameters)
        self.label_V1.setGeometry(QtCore.QRect(130, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_V1.setFont(font)
        self.label_V1.setObjectName(_fromUtf8("label_V1"))
        self.label_step = QtGui.QLabel(self.groupBox_parameters)
        self.label_step.setGeometry(QtCore.QRect(100, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_step.setFont(font)
        self.label_step.setText(_fromUtf8(""))
        self.label_step.setObjectName(_fromUtf8("label_step"))
        self.label_Step = QtGui.QLabel(self.groupBox_parameters)
        self.label_Step.setGeometry(QtCore.QRect(50, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Step.setFont(font)
        self.label_Step.setObjectName(_fromUtf8("label_Step"))
        self.label_U1 = QtGui.QLabel(self.groupBox_parameters)
        self.label_U1.setGeometry(QtCore.QRect(240, 50, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_U1.setFont(font)
        self.label_U1.setObjectName(_fromUtf8("label_U1"))
        self.label_P1 = QtGui.QLabel(self.groupBox_parameters)
        self.label_P1.setGeometry(QtCore.QRect(30, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_P1.setFont(font)
        self.label_P1.setObjectName(_fromUtf8("label_P1"))
        self.label_Time = QtGui.QLabel(self.groupBox_parameters)
        self.label_Time.setGeometry(QtCore.QRect(150, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Time.setFont(font)
        self.label_Time.setObjectName(_fromUtf8("label_Time"))
        self.label_time = QtGui.QLabel(self.groupBox_parameters)
        self.label_time.setGeometry(QtCore.QRect(200, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_time.setFont(font)
        self.label_time.setText(_fromUtf8(""))
        self.label_time.setObjectName(_fromUtf8("label_time"))
        self.label_timeunit = QtGui.QLabel(self.groupBox_parameters)
        self.label_timeunit.setGeometry(QtCore.QRect(260, 20, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_timeunit.setFont(font)
        self.label_timeunit.setObjectName(_fromUtf8("label_timeunit"))
        self.label_U2 = QtGui.QLabel(self.groupBox_parameters)
        self.label_U2.setGeometry(QtCore.QRect(240, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_U2.setFont(font)
        self.label_U2.setObjectName(_fromUtf8("label_U2"))
        self.label_P2 = QtGui.QLabel(self.groupBox_parameters)
        self.label_P2.setGeometry(QtCore.QRect(30, 80, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_P2.setFont(font)
        self.label_P2.setObjectName(_fromUtf8("label_P2"))
        self.label_V2 = QtGui.QLabel(self.groupBox_parameters)
        self.label_V2.setGeometry(QtCore.QRect(130, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_V2.setFont(font)
        self.label_V2.setObjectName(_fromUtf8("label_V2"))
        self.label_U3 = QtGui.QLabel(self.groupBox_parameters)
        self.label_U3.setGeometry(QtCore.QRect(240, 110, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_U3.setFont(font)
        self.label_U3.setObjectName(_fromUtf8("label_U3"))
        self.label_P3 = QtGui.QLabel(self.groupBox_parameters)
        self.label_P3.setGeometry(QtCore.QRect(30, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_P3.setFont(font)
        self.label_P3.setObjectName(_fromUtf8("label_P3"))
        self.label_V3 = QtGui.QLabel(self.groupBox_parameters)
        self.label_V3.setGeometry(QtCore.QRect(130, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_V3.setFont(font)
        self.label_V3.setObjectName(_fromUtf8("label_V3"))
        self.label_U4 = QtGui.QLabel(self.groupBox_parameters)
        self.label_U4.setGeometry(QtCore.QRect(240, 140, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_U4.setFont(font)
        self.label_U4.setObjectName(_fromUtf8("label_U4"))
        self.label_P4 = QtGui.QLabel(self.groupBox_parameters)
        self.label_P4.setGeometry(QtCore.QRect(30, 140, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_P4.setFont(font)
        self.label_P4.setObjectName(_fromUtf8("label_P4"))
        self.label_V4 = QtGui.QLabel(self.groupBox_parameters)
        self.label_V4.setGeometry(QtCore.QRect(130, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_V4.setFont(font)
        self.label_V4.setObjectName(_fromUtf8("label_V4"))
        self.label_U5 = QtGui.QLabel(self.groupBox_parameters)
        self.label_U5.setGeometry(QtCore.QRect(240, 170, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_U5.setFont(font)
        self.label_U5.setObjectName(_fromUtf8("label_U5"))
        self.label_P5 = QtGui.QLabel(self.groupBox_parameters)
        self.label_P5.setGeometry(QtCore.QRect(30, 170, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_P5.setFont(font)
        self.label_P5.setObjectName(_fromUtf8("label_P5"))
        self.label_V5 = QtGui.QLabel(self.groupBox_parameters)
        self.label_V5.setGeometry(QtCore.QRect(130, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_V5.setFont(font)
        self.label_V5.setObjectName(_fromUtf8("label_V5"))
        self.label_U6 = QtGui.QLabel(self.groupBox_parameters)
        self.label_U6.setGeometry(QtCore.QRect(240, 200, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_U6.setFont(font)
        self.label_U6.setObjectName(_fromUtf8("label_U6"))
        self.label_P6 = QtGui.QLabel(self.groupBox_parameters)
        self.label_P6.setGeometry(QtCore.QRect(30, 200, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_P6.setFont(font)
        self.label_P6.setObjectName(_fromUtf8("label_P6"))
        self.label_V6 = QtGui.QLabel(self.groupBox_parameters)
        self.label_V6.setGeometry(QtCore.QRect(130, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_V6.setFont(font)
        self.label_V6.setObjectName(_fromUtf8("label_V6"))
        self.tabWidget_visa = QtGui.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget_visa.setGeometry(QtCore.QRect(10, 10, 321, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_visa.setFont(font)
        self.tabWidget_visa.setObjectName(_fromUtf8("tabWidget_visa"))
        self.tab_228 = QtGui.QWidget()
        self.tab_228.setObjectName(_fromUtf8("tab_228"))
        self.label_chooseVisa_1 = QtGui.QLabel(self.tab_228)
        self.label_chooseVisa_1.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_1.setFont(font)
        self.label_chooseVisa_1.setObjectName(_fromUtf8("label_chooseVisa_1"))
        self.pushButton_select_1 = QtGui.QPushButton(self.tab_228)
        self.pushButton_select_1.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_1.setFont(font)
        self.pushButton_select_1.setObjectName(_fromUtf8("pushButton_select_1"))
        self.comboBox_visa_1 = QtGui.QComboBox(self.tab_228)
        self.comboBox_visa_1.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_1.setFont(font)
        self.comboBox_visa_1.setObjectName(_fromUtf8("comboBox_visa_1"))
        self.label_visaname_1 = QtGui.QLabel(self.tab_228)
        self.label_visaname_1.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_1.setFont(font)
        self.label_visaname_1.setObjectName(_fromUtf8("label_visaname_1"))
        self.pushButton_close_1 = QtGui.QPushButton(self.tab_228)
        self.pushButton_close_1.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_1.setFont(font)
        self.pushButton_close_1.setObjectName(_fromUtf8("pushButton_close_1"))
        self.pushButton_update_1 = QtGui.QPushButton(self.tab_228)
        self.pushButton_update_1.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_1.setFont(font)
        self.pushButton_update_1.setObjectName(_fromUtf8("pushButton_update_1"))
        self.label_visa_1 = QtGui.QLabel(self.tab_228)
        self.label_visa_1.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_1.setFont(font)
        self.label_visa_1.setText(_fromUtf8(""))
        self.label_visa_1.setObjectName(_fromUtf8("label_visa_1"))
        self.tabWidget_visa.addTab(self.tab_228, _fromUtf8(""))
        self.tab_229 = QtGui.QWidget()
        self.tab_229.setObjectName(_fromUtf8("tab_229"))
        self.pushButton_update_2 = QtGui.QPushButton(self.tab_229)
        self.pushButton_update_2.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_2.setFont(font)
        self.pushButton_update_2.setObjectName(_fromUtf8("pushButton_update_2"))
        self.pushButton_close_2 = QtGui.QPushButton(self.tab_229)
        self.pushButton_close_2.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_2.setFont(font)
        self.pushButton_close_2.setObjectName(_fromUtf8("pushButton_close_2"))
        self.pushButton_select_2 = QtGui.QPushButton(self.tab_229)
        self.pushButton_select_2.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_2.setFont(font)
        self.pushButton_select_2.setObjectName(_fromUtf8("pushButton_select_2"))
        self.comboBox_visa_2 = QtGui.QComboBox(self.tab_229)
        self.comboBox_visa_2.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_2.setFont(font)
        self.comboBox_visa_2.setObjectName(_fromUtf8("comboBox_visa_2"))
        self.label_visaname_2 = QtGui.QLabel(self.tab_229)
        self.label_visaname_2.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_2.setFont(font)
        self.label_visaname_2.setObjectName(_fromUtf8("label_visaname_2"))
        self.label_chooseVisa_2 = QtGui.QLabel(self.tab_229)
        self.label_chooseVisa_2.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_2.setFont(font)
        self.label_chooseVisa_2.setObjectName(_fromUtf8("label_chooseVisa_2"))
        self.label_visa_2 = QtGui.QLabel(self.tab_229)
        self.label_visa_2.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_2.setFont(font)
        self.label_visa_2.setText(_fromUtf8(""))
        self.label_visa_2.setObjectName(_fromUtf8("label_visa_2"))
        self.tabWidget_visa.addTab(self.tab_229, _fromUtf8(""))
        self.tab_230 = QtGui.QWidget()
        self.tab_230.setObjectName(_fromUtf8("tab_230"))
        self.pushButton_update_3 = QtGui.QPushButton(self.tab_230)
        self.pushButton_update_3.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_3.setFont(font)
        self.pushButton_update_3.setObjectName(_fromUtf8("pushButton_update_3"))
        self.pushButton_close_3 = QtGui.QPushButton(self.tab_230)
        self.pushButton_close_3.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_3.setFont(font)
        self.pushButton_close_3.setObjectName(_fromUtf8("pushButton_close_3"))
        self.pushButton_select_3 = QtGui.QPushButton(self.tab_230)
        self.pushButton_select_3.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_3.setFont(font)
        self.pushButton_select_3.setObjectName(_fromUtf8("pushButton_select_3"))
        self.comboBox_visa_3 = QtGui.QComboBox(self.tab_230)
        self.comboBox_visa_3.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_3.setFont(font)
        self.comboBox_visa_3.setObjectName(_fromUtf8("comboBox_visa_3"))
        self.label_visaname_3 = QtGui.QLabel(self.tab_230)
        self.label_visaname_3.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_3.setFont(font)
        self.label_visaname_3.setObjectName(_fromUtf8("label_visaname_3"))
        self.label_chooseVisa_3 = QtGui.QLabel(self.tab_230)
        self.label_chooseVisa_3.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_3.setFont(font)
        self.label_chooseVisa_3.setObjectName(_fromUtf8("label_chooseVisa_3"))
        self.label_visa_3 = QtGui.QLabel(self.tab_230)
        self.label_visa_3.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_3.setFont(font)
        self.label_visa_3.setText(_fromUtf8(""))
        self.label_visa_3.setObjectName(_fromUtf8("label_visa_3"))
        self.tabWidget_visa.addTab(self.tab_230, _fromUtf8(""))
        self.tab_231 = QtGui.QWidget()
        self.tab_231.setObjectName(_fromUtf8("tab_231"))
        self.pushButton_update_4 = QtGui.QPushButton(self.tab_231)
        self.pushButton_update_4.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_4.setFont(font)
        self.pushButton_update_4.setObjectName(_fromUtf8("pushButton_update_4"))
        self.pushButton_close_4 = QtGui.QPushButton(self.tab_231)
        self.pushButton_close_4.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_4.setFont(font)
        self.pushButton_close_4.setObjectName(_fromUtf8("pushButton_close_4"))
        self.pushButton_select_4 = QtGui.QPushButton(self.tab_231)
        self.pushButton_select_4.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_4.setFont(font)
        self.pushButton_select_4.setObjectName(_fromUtf8("pushButton_select_4"))
        self.comboBox_visa_4 = QtGui.QComboBox(self.tab_231)
        self.comboBox_visa_4.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_4.setFont(font)
        self.comboBox_visa_4.setObjectName(_fromUtf8("comboBox_visa_4"))
        self.label_visaname_4 = QtGui.QLabel(self.tab_231)
        self.label_visaname_4.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_4.setFont(font)
        self.label_visaname_4.setObjectName(_fromUtf8("label_visaname_4"))
        self.label_chooseVisa_4 = QtGui.QLabel(self.tab_231)
        self.label_chooseVisa_4.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_4.setFont(font)
        self.label_chooseVisa_4.setObjectName(_fromUtf8("label_chooseVisa_4"))
        self.label_visa_4 = QtGui.QLabel(self.tab_231)
        self.label_visa_4.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_4.setFont(font)
        self.label_visa_4.setText(_fromUtf8(""))
        self.label_visa_4.setObjectName(_fromUtf8("label_visa_4"))
        self.tabWidget_visa.addTab(self.tab_231, _fromUtf8(""))
        self.tab_232 = QtGui.QWidget()
        self.tab_232.setObjectName(_fromUtf8("tab_232"))
        self.pushButton_update_5 = QtGui.QPushButton(self.tab_232)
        self.pushButton_update_5.setGeometry(QtCore.QRect(230, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_update_5.setFont(font)
        self.pushButton_update_5.setObjectName(_fromUtf8("pushButton_update_5"))
        self.pushButton_close_5 = QtGui.QPushButton(self.tab_232)
        self.pushButton_close_5.setGeometry(QtCore.QRect(130, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_close_5.setFont(font)
        self.pushButton_close_5.setObjectName(_fromUtf8("pushButton_close_5"))
        self.pushButton_select_5 = QtGui.QPushButton(self.tab_232)
        self.pushButton_select_5.setGeometry(QtCore.QRect(30, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_select_5.setFont(font)
        self.pushButton_select_5.setObjectName(_fromUtf8("pushButton_select_5"))
        self.comboBox_visa_5 = QtGui.QComboBox(self.tab_232)
        self.comboBox_visa_5.setGeometry(QtCore.QRect(10, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_visa_5.setFont(font)
        self.comboBox_visa_5.setObjectName(_fromUtf8("comboBox_visa_5"))
        self.label_visaname_5 = QtGui.QLabel(self.tab_232)
        self.label_visaname_5.setGeometry(QtCore.QRect(20, 120, 181, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_visaname_5.setFont(font)
        self.label_visaname_5.setObjectName(_fromUtf8("label_visaname_5"))
        self.label_chooseVisa_5 = QtGui.QLabel(self.tab_232)
        self.label_chooseVisa_5.setGeometry(QtCore.QRect(20, 0, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_chooseVisa_5.setFont(font)
        self.label_chooseVisa_5.setObjectName(_fromUtf8("label_chooseVisa_5"))
        self.label_visa_5 = QtGui.QLabel(self.tab_232)
        self.label_visa_5.setGeometry(QtCore.QRect(0, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_visa_5.setFont(font)
        self.label_visa_5.setText(_fromUtf8(""))
        self.label_visa_5.setObjectName(_fromUtf8("label_visa_5"))
        self.tabWidget_visa.addTab(self.tab_232, _fromUtf8(""))
        self.textEdit = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setGeometry(QtCore.QRect(10, 250, 321, 91))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.curvewidget_1 = CurveWidget(self.scrollAreaWidgetContents)
        self.curvewidget_1.setGeometry(QtCore.QRect(350, 10, 721, 421))
        self.curvewidget_1.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_1.setObjectName(_fromUtf8("curvewidget_1"))
        self.curvewidget_2 = CurveWidget(self.scrollAreaWidgetContents)
        self.curvewidget_2.setGeometry(QtCore.QRect(1080, 10, 721, 421))
        self.curvewidget_2.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_2.setObjectName(_fromUtf8("curvewidget_2"))
        self.curvewidget_3 = CurveWidget(self.scrollAreaWidgetContents)
        self.curvewidget_3.setGeometry(QtCore.QRect(350, 460, 721, 421))
        self.curvewidget_3.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_3.setObjectName(_fromUtf8("curvewidget_3"))
        self.curvewidget_4 = CurveWidget(self.scrollAreaWidgetContents)
        self.curvewidget_4.setGeometry(QtCore.QRect(1080, 460, 721, 421))
        self.curvewidget_4.setOrientation(QtCore.Qt.Horizontal)
        self.curvewidget_4.setObjectName(_fromUtf8("curvewidget_4"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionArray_Builder = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionArray_Builder.setFont(font)
        self.actionArray_Builder.setObjectName(_fromUtf8("actionArray_Builder"))
        self.actionAgilent_Single_scan = QtGui.QAction(MainWindow)
        self.actionAgilent_Single_scan.setObjectName(_fromUtf8("actionAgilent_Single_scan"))
        self.actionKeithley_Single_scan = QtGui.QAction(MainWindow)
        self.actionKeithley_Single_scan.setObjectName(_fromUtf8("actionKeithley_Single_scan"))
        self.actionKeithley__Sweep = QtGui.QAction(MainWindow)
        self.actionKeithley__Sweep.setObjectName(_fromUtf8("actionKeithley__Sweep"))
        self.actionLockIn_Single_Scan = QtGui.QAction(MainWindow)
        self.actionLockIn_Single_Scan.setObjectName(_fromUtf8("actionLockIn_Single_Scan"))
        self.actionResonant_Single_Scan = QtGui.QAction(MainWindow)
        self.actionResonant_Single_Scan.setObjectName(_fromUtf8("actionResonant_Single_Scan"))
        self.actionKeithley_Stepper_Single_Scan = QtGui.QAction(MainWindow)
        self.actionKeithley_Stepper_Single_Scan.setObjectName(_fromUtf8("actionKeithley_Stepper_Single_Scan"))
        self.actionSee_Visa_List = QtGui.QAction(MainWindow)
        self.actionSee_Visa_List.setObjectName(_fromUtf8("actionSee_Visa_List"))
        self.actionTwo_s_with_Lock_in = QtGui.QAction(MainWindow)
        self.actionTwo_s_with_Lock_in.setObjectName(_fromUtf8("actionTwo_s_with_Lock_in"))
        self.actionSweep_Scan = QtGui.QAction(MainWindow)
        self.actionSweep_Scan.setObjectName(_fromUtf8("actionSweep_Scan"))
        self.actionLockInSweep = QtGui.QAction(MainWindow)
        self.actionLockInSweep.setObjectName(_fromUtf8("actionLockInSweep"))
        self.actionDouble_Lock_In = QtGui.QAction(MainWindow)
        self.actionDouble_Lock_In.setObjectName(_fromUtf8("actionDouble_Lock_In"))
        self.actionVoltage_Bias = QtGui.QAction(MainWindow)
        self.actionVoltage_Bias.setObjectName(_fromUtf8("actionVoltage_Bias"))
        self.actionCurrent_Bias = QtGui.QAction(MainWindow)
        self.actionCurrent_Bias.setObjectName(_fromUtf8("actionCurrent_Bias"))
        self.actionJV_1 = QtGui.QAction(MainWindow)
        self.actionJV_1.setObjectName(_fromUtf8("actionJV_1"))
        self.actionJV_2 = QtGui.QAction(MainWindow)
        self.actionJV_2.setObjectName(_fromUtf8("actionJV_2"))
        self.actionJV_3 = QtGui.QAction(MainWindow)
        self.actionJV_3.setObjectName(_fromUtf8("actionJV_3"))
        self.actionJS_1 = QtGui.QAction(MainWindow)
        self.actionJS_1.setObjectName(_fromUtf8("actionJS_1"))
        self.actionJS_2 = QtGui.QAction(MainWindow)
        self.actionJS_2.setObjectName(_fromUtf8("actionJS_2"))
        self.actionRS_1 = QtGui.QAction(MainWindow)
        self.actionRS_1.setObjectName(_fromUtf8("actionRS_1"))
        self.actionRS_2 = QtGui.QAction(MainWindow)
        self.actionRS_2.setObjectName(_fromUtf8("actionRS_2"))
        self.actionJS_3 = QtGui.QAction(MainWindow)
        self.actionJS_3.setObjectName(_fromUtf8("actionJS_3"))
        self.actionRS_3 = QtGui.QAction(MainWindow)
        self.actionRS_3.setObjectName(_fromUtf8("actionRS_3"))
        self.actionBW_1 = QtGui.QAction(MainWindow)
        self.actionBW_1.setObjectName(_fromUtf8("actionBW_1"))
        self.actionBW_2 = QtGui.QAction(MainWindow)
        self.actionBW_2.setObjectName(_fromUtf8("actionBW_2"))
        self.actionBW_3 = QtGui.QAction(MainWindow)
        self.actionBW_3.setObjectName(_fromUtf8("actionBW_3"))
        self.actionST_1 = QtGui.QAction(MainWindow)
        self.actionST_1.setObjectName(_fromUtf8("actionST_1"))
        self.actionST_2 = QtGui.QAction(MainWindow)
        self.actionST_2.setObjectName(_fromUtf8("actionST_2"))
        self.actionST_3 = QtGui.QAction(MainWindow)
        self.actionST_3.setObjectName(_fromUtf8("actionST_3"))

        self.retranslateUi(MainWindow)
        self.tabWidget_visa.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_condition.setTitle(_translate("MainWindow", "Condition", None))
        self.groupBox_control.setTitle(_translate("MainWindow", "Control", None))
        self.pushButton_Start.setText(_translate("MainWindow", "Start", None))
        self.pushButton_Pause.setText(_translate("MainWindow", "Pause", None))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop", None))
        self.groupBox_parameters.setTitle(_translate("MainWindow", "Parameters", None))
        self.label_V1.setText(_translate("MainWindow", "Value 1", None))
        self.label_Step.setText(_translate("MainWindow", "Steps:", None))
        self.label_U1.setText(_translate("MainWindow", "Unit 1", None))
        self.label_P1.setText(_translate("MainWindow", "Parameter 1:", None))
        self.label_Time.setText(_translate("MainWindow", "Time:", None))
        self.label_timeunit.setText(_translate("MainWindow", "s", None))
        self.label_U2.setText(_translate("MainWindow", "Unit 2", None))
        self.label_P2.setText(_translate("MainWindow", "Parameter 2:", None))
        self.label_V2.setText(_translate("MainWindow", "Value 2", None))
        self.label_U3.setText(_translate("MainWindow", "Unit 3", None))
        self.label_P3.setText(_translate("MainWindow", "Parameter 3:", None))
        self.label_V3.setText(_translate("MainWindow", "Value 3", None))
        self.label_U4.setText(_translate("MainWindow", "Unit 4", None))
        self.label_P4.setText(_translate("MainWindow", "Parameter 4:", None))
        self.label_V4.setText(_translate("MainWindow", "Value 4", None))
        self.label_U5.setText(_translate("MainWindow", "Unit 5", None))
        self.label_P5.setText(_translate("MainWindow", "Parameter 5:", None))
        self.label_V5.setText(_translate("MainWindow", "Value 5", None))
        self.label_U6.setText(_translate("MainWindow", "Unit 6", None))
        self.label_P6.setText(_translate("MainWindow", "Parameter 6:", None))
        self.label_V6.setText(_translate("MainWindow", "Value 6", None))
        self.label_chooseVisa_1.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.pushButton_select_1.setText(_translate("MainWindow", "Select", None))
        self.label_visaname_1.setText(_translate("MainWindow", "VISA name:", None))
        self.pushButton_close_1.setText(_translate("MainWindow", "Close", None))
        self.pushButton_update_1.setText(_translate("MainWindow", "Update", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_228), _translate("MainWindow", "Visa1", None))
        self.pushButton_update_2.setText(_translate("MainWindow", "Update", None))
        self.pushButton_close_2.setText(_translate("MainWindow", "Close", None))
        self.pushButton_select_2.setText(_translate("MainWindow", "Select", None))
        self.label_visaname_2.setText(_translate("MainWindow", "VISA name:", None))
        self.label_chooseVisa_2.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_229), _translate("MainWindow", "Visa2", None))
        self.pushButton_update_3.setText(_translate("MainWindow", "Update", None))
        self.pushButton_close_3.setText(_translate("MainWindow", "Close", None))
        self.pushButton_select_3.setText(_translate("MainWindow", "Select", None))
        self.label_visaname_3.setText(_translate("MainWindow", "VISA name:", None))
        self.label_chooseVisa_3.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_230), _translate("MainWindow", "Visa3", None))
        self.pushButton_update_4.setText(_translate("MainWindow", "Update", None))
        self.pushButton_close_4.setText(_translate("MainWindow", "Close", None))
        self.pushButton_select_4.setText(_translate("MainWindow", "Select", None))
        self.label_visaname_4.setText(_translate("MainWindow", "VISA name:", None))
        self.label_chooseVisa_4.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_231), _translate("MainWindow", "Visa4", None))
        self.pushButton_update_5.setText(_translate("MainWindow", "Update", None))
        self.pushButton_close_5.setText(_translate("MainWindow", "Close", None))
        self.pushButton_select_5.setText(_translate("MainWindow", "Select", None))
        self.label_visaname_5.setText(_translate("MainWindow", "VISA name:", None))
        self.label_chooseVisa_5.setText(_translate("MainWindow", "Choose  Visa:", None))
        self.tabWidget_visa.setTabText(self.tabWidget_visa.indexOf(self.tab_232), _translate("MainWindow", "Visa5", None))
        self.actionArray_Builder.setText(_translate("MainWindow", "Array Builder", None))
        self.actionAgilent_Single_scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionKeithley_Single_scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionKeithley__Sweep.setText(_translate("MainWindow", " Sweep", None))
        self.actionLockIn_Single_Scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionResonant_Single_Scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionKeithley_Stepper_Single_Scan.setText(_translate("MainWindow", "Single Scan", None))
        self.actionSee_Visa_List.setText(_translate("MainWindow", "See Visa List", None))
        self.actionTwo_s_with_Lock_in.setText(_translate("MainWindow", "Two s with Lock-in", None))
        self.actionSweep_Scan.setText(_translate("MainWindow", "Sweep Scan", None))
        self.actionLockInSweep.setText(_translate("MainWindow", "Sweep Scan", None))
        self.actionDouble_Lock_In.setText(_translate("MainWindow", "Double Lock-In", None))
        self.actionVoltage_Bias.setText(_translate("MainWindow", "Voltage", None))
        self.actionCurrent_Bias.setText(_translate("MainWindow", "Current", None))
        self.actionJV_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionJV_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionJV_3.setText(_translate("MainWindow", "Program 3", None))
        self.actionJS_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionJS_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionRS_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionRS_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionJS_3.setText(_translate("MainWindow", "Program 3", None))
        self.actionRS_3.setText(_translate("MainWindow", "Program 3", None))
        self.actionBW_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionBW_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionBW_3.setText(_translate("MainWindow", "Program 3", None))
        self.actionST_1.setText(_translate("MainWindow", "Program 1", None))
        self.actionST_2.setText(_translate("MainWindow", "Program 2", None))
        self.actionST_3.setText(_translate("MainWindow", "Program 3", None))

from guiqwt.plot import CurveWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

